version: '3.8'

services:
  webgoat_scan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/wd/app/output
      - ./temp_dir_for_gitzips/webgoat:/wd/app/temp_dir_for_gitzips
    command: >
      sh -c "
      echo 'Starting WebGoat scan...' &&
      python3 run_regexploit.py --directory temp_dir_for_gitzips --repo_url https://github.com/WebGoat/WebGoat --output output/data1.json --git-ignore
      "

  dvwa_scan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/wd/app/output
      - ./temp_dir_for_gitzips/dvwa:/wd/app/temp_dir_for_gitzips
    command: >
      sh -c "
      echo 'Starting DVWA scan...' &&
      python3 run_regexploit.py --directory temp_dir_for_gitzips --repo_url https://github.com/digininja/DVWA --output output/data2.json --git-ignore
      "

  nodegoat_scan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/wd/app/output
      - ./temp_dir_for_gitzips/nodegoat:/wd/app/temp_dir_for_gitzips
    command: >
      sh -c "
      echo 'Starting NodeGoat scan...' &&
      python3 run_regexploit.py --directory temp_dir_for_gitzips --repo_url https://github.com/OWASP/NodeGoat --output output/data3.json --git-ignore
      "
